import XCTest
@testable import VolleyCore

final class AudioFeatureTests: XCTestCase {
    func testMatchesAndroidGoldenWithPrimingGapOverlapAndNonintegralResampling() throws {
        let extractor = AudioFeatureExtractor()
        let rate = 22_050
        for offset in stride(from: 0, to: 11_025, by: 317) {
            let count = min(317, 11_025 - offset)
            let samples = (0..<count).map { Float((offset + $0) % 71 - 35) / 64 }
            let time = Double(offset) / Double(rate) - 0.02 + (offset >= 6340 ? 0.05 : 0)
            try extractor.push(samples, timestampSeconds: time, sampleRate: rate)
            if offset == 3170 { try extractor.push(samples, timestampSeconds: time, sampleRate: rate) }
        }
        let times = [0.0, 0.25, 0.5, 0.9]
        let actual = try extractor.finishAndPool(times)
        // Generated by compiling the checked-in Android AudioFeatureExtractor,
        // Radix2Fft, FeatureMath, FeatureSchema, NanoProfiler with the same PCM.
        let expected: [Float] = [
            1, 0.3144979, 0.5467224, 1.7506975, 0.2085529, 2.6881196, 0.0035209025, 0.0070415437, 0.535, 0.5125, 0.2530808, 0.015096922, 10, 28.05607, 0.0052144853, 18.177813, 0, 27.586002, 1.2361681e-5, 26.564962, 2.6811476e-4, 25.537203, 2.976663e-4, 24.945072, 3.3934563e-4, 24.357494, 0.0051879724,
            1, 0.28375244, 0.5467224, 2.8071082, 0.24650872, 1.2843848, 0.04707305, 0.06122923, 0.795, 0.5125, 0.30866823, 0.024580846, 10, 26.283903, 58.1857, 22.54866, 22.295418, 25.71555, 25.715448, 24.927097, 24.926384, 23.836271, 23.833893, 23.17697, 23.167757, 22.418621, 22.38485,
            1, 0.29822844, 0.5466919, 2.2031577, 0.21655232, 2.0197253, 0.03439644, 0.058893412, 0.69499993, 0.50991726, 0.28590858, 0, 10, 27.805204, 61.306313, 22.728802, 22.31404, 27.302345, 27.260834, 26.35904, 26.30593, 25.307865, 25.27182, 24.716408, 24.662403, 24.14109, 24.051888,
            1, 0.24813016, 0.5466919, 2.2031577, 0, 7.8169413, 0.028404556, 0, 0.5375, 0.50991726, 0.30162275, 0, 10, 27.805204, 61.306313, 22.728802, 22.31404, 27.302345, 27.260834, 26.35904, 26.30593, 25.307865, 25.27182, 24.716408, 24.662403, 24.14109, 24.051888
        ]
        XCTAssertEqual(actual.count, expected.count)
        XCTAssertEqual(extractor.resampledOutputSamples, 8481)
        XCTAssertEqual(extractor.audioFeatureFrameCount, 11)
        for i in expected.indices {
            XCTAssertEqual(actual[i], expected[i], accuracy: max(2e-6, abs(expected[i]) * 2e-6),
                           "row \(i / 27), \(AudioFeatureExtractor.featureNames[i % 27])")
        }
        XCTAssertEqual(try extractor.finishAndPool(times), actual, "Re-pooling must not flush PCM twice")
    }

    func testChunked48kHzAndProgress() throws {
        let extractor = AudioFeatureExtractor()
        let sampleRate = 48_000
        for offset in stride(from: 0, to: sampleRate, by: 1024) {
            let count = min(1024, sampleRate - offset)
            let samples = (0..<count).map { Float(sin(2 * Double.pi * 440 * Double(offset + $0) / Double(sampleRate))) }
            try extractor.push(samples, timestampSeconds: Double(offset) / Double(sampleRate), sampleRate: sampleRate)
        }
        var progress: [Double] = [], details: [String] = []
        let features = try extractor.finishAndPool([0, 0.25, 0.5, 0.75]) { fraction, detail in
            progress.append(fraction); details.append(detail)
        }
        XCTAssertEqual(features.count, 4 * 27)
        XCTAssertGreaterThanOrEqual(extractor.resampledOutputSamples, 15_999)
        for row in 0..<4 { XCTAssertEqual(features[row * 27], 1) }
        XCTAssertTrue(features.allSatisfy(\.isFinite))
        XCTAssertEqual(progress, [0.82, 0.88, 0.95, 0.99])
        XCTAssertEqual(details, ["Flushing resampler + final FFT frames",
                                 "Computing audio ranks + rolling noise floors",
                                 "Pooling audio features to 4 Hz video timestamps",
                                 "Audio DSP complete; preparing feature cache"])
    }

    func testNoAudioAndSilenceAreDistinct() throws {
        XCTAssertEqual(try AudioFeatureExtractor().finishAndPool([0, 0.25]), [Float](repeating: 0, count: 54))
        let extractor = AudioFeatureExtractor()
        try extractor.push([Float](repeating: 0, count: 800), timestampSeconds: 0, sampleRate: 16_000)
        let values = try extractor.finishAndPool([0])
        XCTAssertEqual(values[0], 1)
        XCTAssertEqual(values[1], 0)
        XCTAssertEqual(values[12], 10)
        XCTAssertTrue(values.allSatisfy(\.isFinite))
    }

    func testRejectsInvalidInputAndLatePushes() throws {
        let extractor = AudioFeatureExtractor()
        XCTAssertThrowsError(try extractor.push([0], timestampSeconds: 0, sampleRate: 0))
        XCTAssertThrowsError(try extractor.push([.nan], timestampSeconds: 0, sampleRate: 16_000))
        try extractor.push([0], timestampSeconds: 0, sampleRate: 16_000)
        XCTAssertThrowsError(try extractor.push([0], timestampSeconds: 0, sampleRate: 48_000))
        XCTAssertThrowsError(try extractor.finishAndPool([.nan]))
        _ = try extractor.finishAndPool([0])
        XCTAssertThrowsError(try extractor.push([0], timestampSeconds: 1, sampleRate: 16_000))
    }

    func testFFTImpulseAndAndroidRollingPercentileCompatibility() {
        XCTAssertEqual(Radix2FFT(size: 8).magnitudes([1, 0, 0, 0, 0, 0, 0, 0]), [1, 1, 1, 1, 1])
        XCTAssertEqual(Radix2FFT(size: 8).magnitudes([1, 1, 1, 1, 1, 1, 1, 1]), [8, 0, 0, 0, 0])
        let floor = AudioFeatureExtractor.rollingPercentile([1, 2, 3, 4, 5, 6, 7], window: 200, percentile: 0.2)
        XCTAssertEqual(floor, [0, 1.2, 1.4, 1.6, 1.8, 0, 2.2])
    }
}
